export const SUPPORTED_SUBDIVISION_COUNTRIES = [
  { name: 'Argentina', code: 'ARG', iso2: 'ar' },
  { name: 'Australia', code: 'AUS', iso2: 'au' },
  { name: 'Austria', code: 'AUT', iso2: 'at' },
  { name: 'Bangladesh', code: 'BGD', iso2: 'bd' },
  { name: 'Belgium', code: 'BEL', iso2: 'be' },
  { name: 'Bolivia', code: 'BOL', iso2: 'bo' },
  { name: 'Brazil', code: 'BRA', iso2: 'br' },
  { name: 'Bulgaria', code: 'BGR', iso2: 'bg' },
  { name: 'Canada', code: 'CAN', iso2: 'ca' },
  { name: 'Chile', code: 'CHL', iso2: 'cl' },
  { name: 'China', code: 'CHN', iso2: 'cn' },
  { name: 'Colombia', code: 'COL', iso2: 'co' },
  { name: 'Costa Rica', code: 'CRI', iso2: 'cr' },
  { name: 'Croatia', code: 'HRV', iso2: 'hr' },
  { name: 'Czech Republic', code: 'CZE', iso2: 'cz' },
  { name: 'Denmark', code: 'DNK', iso2: 'dk' },
  { name: 'Dominican Republic', code: 'DOM', iso2: 'do' },
  { name: 'Ecuador', code: 'ECU', iso2: 'ec' },
  { name: 'Egypt', code: 'EGY', iso2: 'eg' },
  { name: 'Finland', code: 'FIN', iso2: 'fi' },
  { name: 'France', code: 'FRA', iso2: 'fr' },
  { name: 'Germany', code: 'DEU', iso2: 'de' },
  { name: 'Greece', code: 'GRC', iso2: 'gr' },
  { name: 'Hungary', code: 'HUN', iso2: 'hu' },
  { name: 'India', code: 'IND', iso2: 'in' },
  { name: 'Indonesia', code: 'IDN', iso2: 'id' },
  { name: 'Ireland', code: 'IRL', iso2: 'ie' },
  { name: 'Israel', code: 'ISR', iso2: 'il' },
  { name: 'Italy', code: 'ITA', iso2: 'it' },
  { name: 'Japan', code: 'JPN', iso2: 'jp' },
  { name: 'Kenya', code: 'KEN', iso2: 'ke' },
  { name: 'Malaysia', code: 'MYS', iso2: 'my' },
  { name: 'Mexico', code: 'MEX', iso2: 'mx' },
  { name: 'Morocco', code: 'MAR', iso2: 'ma' },
  { name: 'Netherlands', code: 'NLD', iso2: 'nl' },
  { name: 'New Zealand', code: 'NZL', iso2: 'nz' },
  { name: 'Nigeria', code: 'NGA', iso2: 'ng' },
  { name: 'Norway', code: 'NOR', iso2: 'no' },
  { name: 'Pakistan', code: 'PAK', iso2: 'pk' },
  { name: 'Peru', code: 'PER', iso2: 'pe' },
  { name: 'Philippines', code: 'PHL', iso2: 'ph' },
  { name: 'Poland', code: 'POL', iso2: 'pl' },
  { name: 'Portugal', code: 'PRT', iso2: 'pt' },
  { name: 'Romania', code: 'ROU', iso2: 'ro' },
  { name: 'Russia', code: 'RUS', iso2: 'ru' },
  { name: 'Saudi Arabia', code: 'SAU', iso2: 'sa' },
  { name: 'South Africa', code: 'ZAF', iso2: 'za' },
  { name: 'South Korea', code: 'KOR', iso2: 'kr' },
  { name: 'Spain', code: 'ESP', iso2: 'es' },
  { name: 'Sweden', code: 'SWE', iso2: 'se' },
  { name: 'Switzerland', code: 'CHE', iso2: 'ch' },
  { name: 'Thailand', code: 'THA', iso2: 'th' },
  { name: 'Turkey', code: 'TUR', iso2: 'tr' },
  { name: 'Ukraine', code: 'UKR', iso2: 'ua' },
  { name: 'United Kingdom', code: 'GBR', iso2: 'gb' },
  { name: 'United States', code: 'USA', iso2: 'us' },
  { name: 'Vietnam', code: 'VNM', iso2: 'vn' }
];

export const WORLD_DATA_URL = 'https://raw.githubusercontent.com/datasets/geo-countries/master/data/countries.geojson';
export const ADMIN1_DATA_URL = 'https://raw.githubusercontent.com/datasets/geo-ne-admin1/master/data/admin1.geojson';
